// Source of truth: 中選會「中選務字第1153150253號公告」第 3–15 頁。
// Regional districts drive the ordinary geographic map. Indigenous districts overlap those
// regions by elector qualification, so they stay as independent contests and are not inferred
// from a clicked township or village.

export type CouncilDistrictKind = 'REGIONAL' | 'PLAINS_INDIGENOUS' | 'MOUNTAIN_INDIGENOUS';

export type CouncilDistrict = {
  area: string;
  id: string;
  jurisdictionId: string;
  kind: CouncilDistrictKind;
  number: number;
  seats: number;
  townships: readonly string[];
  villageGroups: readonly {
    township: string;
    villages: readonly string[];
  }[];
};

type DistrictInput = Omit<CouncilDistrict, 'id' | 'jurisdictionId'>;

const r = (number: number, seats: number, townships: readonly string[]): DistrictInput => ({
  area: townships.join('、'),
  kind: 'REGIONAL',
  number,
  seats,
  townships,
  villageGroups: [],
});

const rv = (
  number: number,
  seats: number,
  township: string,
  villages: readonly string[],
): DistrictInput => ({
  area: `${township}${villages.join('、')}`,
  kind: 'REGIONAL',
  number,
  seats,
  townships: [],
  villageGroups: [{ township, villages }],
});

const i = (
  number: number,
  seats: number,
  kind: Exclude<CouncilDistrictKind, 'REGIONAL'>,
  area: string,
): DistrictInput => ({ area, kind, number, seats, townships: [], villageGroups: [] });

const districtInputs: Record<string, readonly DistrictInput[]> = {
  TPE: [
    r(1, 12, ['北投區', '士林區']),
    r(2, 9, ['內湖區', '南港區']),
    r(3, 9, ['松山區', '信義區']),
    r(4, 8, ['中山區', '大同區']),
    r(5, 8, ['中正區', '萬華區']),
    r(6, 13, ['大安區', '文山區']),
    i(7, 1, 'PLAINS_INDIGENOUS', '臺北市之平地原住民'),
    i(8, 1, 'MOUNTAIN_INDIGENOUS', '臺北市之山地原住民'),
  ],
  NTP: [
    r(1, 4, ['石門區', '三芝區', '淡水區', '八里區']),
    r(2, 5, ['林口區', '五股區', '泰山區']),
    r(3, 7, ['新莊區']),
    r(4, 9, ['蘆洲區', '三重區']),
    r(5, 9, ['板橋區']),
    r(6, 6, ['中和區']),
    r(7, 3, ['永和區']),
    r(8, 9, ['樹林區', '鶯歌區', '土城區', '三峽區']),
    r(9, 5, ['新店區', '深坑區', '石碇區', '坪林區', '烏來區']),
    r(10, 1, ['平溪區', '瑞芳區', '雙溪區', '貢寮區']),
    r(11, 4, ['金山區', '萬里區', '汐止區']),
    i(12, 4, 'PLAINS_INDIGENOUS', '新北市之平地原住民'),
    i(13, 2, 'MOUNTAIN_INDIGENOUS', '新北市之山地原住民'),
  ],
  TAO: [
    r(1, 12, ['桃園區']),
    r(2, 5, ['龜山區']),
    r(3, 5, ['八德區']),
    r(4, 4, ['蘆竹區']),
    r(5, 2, ['大園區']),
    r(6, 2, ['大溪區', '復興區']),
    r(7, 11, ['中壢區']),
    r(8, 6, ['平鎮區']),
    r(9, 4, ['楊梅區']),
    r(10, 3, ['龍潭區']),
    r(11, 1, ['新屋區']),
    r(12, 2, ['觀音區']),
    i(13, 4, 'PLAINS_INDIGENOUS', '桃園市之平地原住民'),
    i(14, 4, 'MOUNTAIN_INDIGENOUS', '桃園市之山地原住民'),
  ],
  TXG: [
    r(1, 3, ['大甲區', '大安區', '外埔區']),
    r(2, 5, ['清水區', '梧棲區', '沙鹿區']),
    r(3, 5, ['龍井區', '大肚區', '烏日區']),
    r(4, 5, ['后里區', '豐原區']),
    r(5, 6, ['神岡區', '大雅區', '潭子區']),
    r(6, 5, ['西屯區']),
    r(7, 4, ['南屯區']),
    r(8, 7, ['北屯區']),
    r(9, 3, ['北區']),
    r(10, 3, ['中區', '西區']),
    r(11, 4, ['東區', '南區']),
    r(12, 4, ['太平區']),
    r(13, 6, ['大里區', '霧峰區']),
    r(14, 2, ['東勢區', '石岡區', '新社區', '和平區']),
    i(15, 1, 'PLAINS_INDIGENOUS', '臺中市之平地原住民'),
    i(
      16,
      1,
      'MOUNTAIN_INDIGENOUS',
      '和平區及大甲區、大安區、外埔區、清水區、后里區、豐原區、神岡區、大雅區、潭子區、東勢區、石岡區、新社區之山地原住民',
    ),
    i(
      17,
      1,
      'MOUNTAIN_INDIGENOUS',
      '梧棲區、沙鹿區、龍井區、大肚區、烏日區、西屯區、南屯區、北屯區、北區、中區、西區、東區、南區、太平區、大里區、霧峰區之山地原住民',
    ),
  ],
  TNN: [
    r(1, 5, ['後壁區', '白河區', '東山區', '鹽水區', '新營區', '柳營區']),
    r(2, 5, ['北門區', '學甲區', '將軍區', '七股區', '佳里區', '西港區']),
    r(3, 3, ['下營區', '六甲區', '麻豆區', '官田區', '大內區']),
    r(4, 1, ['楠西區', '南化區', '玉井區', '左鎮區']),
    r(5, 5, ['善化區', '安定區', '新市區', '山上區', '新化區']),
    r(6, 6, ['安南區']),
    r(7, 7, ['永康區']),
    r(8, 6, ['北區', '中西區']),
    r(9, 6, ['安平區', '南區']),
    r(10, 5, ['東區']),
    r(11, 6, ['仁德區', '歸仁區', '關廟區', '龍崎區']),
    i(12, 1, 'PLAINS_INDIGENOUS', '臺南市之平地原住民'),
    i(13, 1, 'MOUNTAIN_INDIGENOUS', '臺南市之山地原住民'),
  ],
  KHH: [
    r(1, 3, [
      '桃源區',
      '那瑪夏區',
      '甲仙區',
      '六龜區',
      '杉林區',
      '內門區',
      '旗山區',
      '美濃區',
      '茂林區',
    ]),
    r(2, 3, ['茄萣區', '湖內區', '路竹區', '阿蓮區', '田寮區']),
    r(3, 5, ['永安區', '岡山區', '燕巢區', '彌陀區', '梓官區', '橋頭區']),
    r(4, 9, ['楠梓區', '左營區']),
    r(5, 5, ['大社區', '仁武區', '鳥松區', '大樹區']),
    r(6, 4, ['鼓山區', '鹽埕區', '旗津區']),
    r(7, 8, ['三民區']),
    r(8, 5, ['前金區', '新興區', '苓雅區']),
    r(9, 8, ['鳳山區']),
    r(10, 7, ['前鎮區', '小港區']),
    r(11, 4, ['大寮區', '林園區']),
    i(12, 1, 'PLAINS_INDIGENOUS', '高雄市之平地原住民'),
    i(
      13,
      1,
      'MOUNTAIN_INDIGENOUS',
      '那瑪夏區及甲仙區、杉林區、內門區、旗山區、茄萣區、湖內區、路竹區、永安區、彌陀區、梓官區、楠梓區、左營區、三民區之山地原住民',
    ),
    i(
      14,
      1,
      'MOUNTAIN_INDIGENOUS',
      '桃源區及六龜區、美濃區、阿蓮區、田寮區、岡山區、燕巢區、橋頭區、鼓山區、鹽埕區、前金區、新興區之山地原住民',
    ),
    i(
      15,
      1,
      'MOUNTAIN_INDIGENOUS',
      '茂林區及大社區、大樹區、仁武區、鳥松區、鳳山區、大寮區、旗津區、苓雅區、前鎮區、小港區、林園區之山地原住民',
    ),
  ],
  HSQ: [
    rv(1, 4, '竹北市', [
      '尚義里',
      '崇義里',
      '新港里',
      '大義里',
      '白地里',
      '大眉里',
      '麻園里',
      '溪州里',
      '新庄里',
      '聯興里',
      '泰和里',
      '新社里',
      '新國里',
      '竹義里',
      '新崙里',
    ]),
    rv(2, 9, '竹北市', [
      '竹北里',
      '竹仁里',
      '福德里',
      '北崙里',
      '中崙里',
      '文化里',
      '興安里',
      '斗崙里',
      '北興里',
      '十興里',
      '鹿場里',
      '東興里',
      '中興里',
      '東平里',
      '東海里',
      '隘口里',
    ]),
    r(3, 5, ['湖口鄉']),
    r(4, 3, ['新豐鄉']),
    r(5, 2, ['關西鎮']),
    r(6, 2, ['新埔鎮']),
    r(7, 1, ['橫山鄉', '尖石鄉']),
    r(8, 1, ['芎林鄉']),
    r(9, 5, ['竹東鎮', '五峰鄉']),
    r(10, 1, ['寶山鄉']),
    r(11, 1, ['北埔鄉', '峨眉鄉']),
    i(12, 1, 'PLAINS_INDIGENOUS', '新竹縣之平地原住民'),
    i(
      13,
      1,
      'MOUNTAIN_INDIGENOUS',
      '尖石鄉及竹北市、湖口鄉、新豐鄉、關西鎮、新埔鎮、橫山鄉之山地原住民',
    ),
    i(14, 1, 'MOUNTAIN_INDIGENOUS', '五峰鄉及芎林鄉、竹東鎮、寶山鄉、北埔鄉、峨眉鄉之山地原住民'),
  ],
  MIA: [
    r(1, 9, ['苗栗市', '公館鄉', '頭屋鄉']),
    r(2, 3, ['銅鑼鄉', '三義鄉', '西湖鄉']),
    r(3, 5, ['通霄鎮', '苑裡鎮']),
    r(4, 9, ['後龍鎮', '造橋鄉', '竹南鎮']),
    r(5, 8, ['頭份市', '三灣鄉', '南庄鄉']),
    r(6, 2, ['大湖鄉', '獅潭鄉', '卓蘭鎮', '泰安鄉']),
    i(7, 1, 'PLAINS_INDIGENOUS', '苗栗縣之平地原住民'),
    i(8, 1, 'MOUNTAIN_INDIGENOUS', '苗栗縣之山地原住民'),
  ],
  CHA: [
    r(1, 12, ['彰化市', '花壇鄉', '芬園鄉']),
    r(2, 7, ['鹿港鎮', '福興鄉', '秀水鄉']),
    r(3, 6, ['和美鎮', '伸港鄉', '線西鄉']),
    r(4, 9, ['員林市', '大村鄉', '永靖鄉']),
    r(5, 5, ['溪湖鎮', '埔鹽鄉', '埔心鄉']),
    r(6, 4, ['田中鎮', '社頭鄉', '二水鄉']),
    r(7, 5, ['北斗鎮', '田尾鄉', '埤頭鄉', '溪州鄉']),
    r(8, 5, ['二林鎮', '大城鄉', '芳苑鄉', '竹塘鄉']),
    i(9, 1, 'PLAINS_INDIGENOUS', '彰化縣之平地原住民'),
    i(10, 1, 'MOUNTAIN_INDIGENOUS', '彰化縣之山地原住民'),
  ],
  NAN: [
    r(1, 10, ['南投市', '名間鄉']),
    r(2, 9, ['草屯鎮', '中寮鄉']),
    r(3, 3, ['集集鎮', '水里鄉', '魚池鄉', '信義鄉']),
    r(4, 5, ['竹山鎮', '鹿谷鄉']),
    r(5, 7, ['埔里鎮', '國姓鄉', '仁愛鄉']),
    i(6, 1, 'PLAINS_INDIGENOUS', '南投縣之平地原住民'),
    i(
      7,
      1,
      'MOUNTAIN_INDIGENOUS',
      '信義鄉及南投市、竹山鎮、集集鎮、名間鄉、鹿谷鄉、水里鄉之山地原住民',
    ),
    i(8, 1, 'MOUNTAIN_INDIGENOUS', '仁愛鄉及草屯鎮、中寮鄉、魚池鄉、國姓鄉、埔里鎮之山地原住民'),
  ],
  YUN: [
    r(1, 10, ['斗六市', '莿桐鄉', '林內鄉']),
    r(2, 6, ['斗南鎮', '古坑鄉', '大埤鄉']),
    r(3, 9, ['虎尾鎮', '土庫鎮', '褒忠鄉', '元長鄉']),
    r(4, 6, ['西螺鎮', '二崙鄉', '崙背鄉']),
    r(5, 7, ['臺西鄉', '麥寮鄉', '東勢鄉', '四湖鄉']),
    r(6, 5, ['北港鎮', '口湖鄉', '水林鄉']),
    i(7, 1, 'PLAINS_INDIGENOUS', '雲林縣之平地原住民'),
    i(8, 1, 'MOUNTAIN_INDIGENOUS', '雲林縣之山地原住民'),
  ],
  CYQ: [
    r(1, 8, ['鹿草鄉', '太保市', '水上鄉']),
    r(2, 8, ['民雄鄉', '新港鄉']),
    r(3, 4, ['大林鎮', '溪口鄉', '梅山鄉']),
    r(4, 6, ['朴子市', '六腳鄉', '東石鄉']),
    r(5, 3, ['布袋鎮', '義竹鄉']),
    r(6, 7, ['中埔鄉', '竹崎鄉', '番路鄉', '大埔鄉', '阿里山鄉']),
    i(7, 1, 'MOUNTAIN_INDIGENOUS', '嘉義縣之山地原住民'),
  ],
  PIF: [
    r(1, 12, ['屏東市']),
    r(2, 8, [
      '長治鄉',
      '麟洛鄉',
      '九如鄉',
      '里港鄉',
      '鹽埔鄉',
      '高樹鄉',
      '三地門鄉',
      '霧臺鄉',
      '瑪家鄉',
    ]),
    r(3, 10, [
      '潮州鎮',
      '萬巒鄉',
      '內埔鄉',
      '竹田鄉',
      '新埤鄉',
      '枋寮鄉',
      '泰武鄉',
      '來義鄉',
      '春日鄉',
    ]),
    r(4, 8, ['東港鎮', '新園鄉', '萬丹鄉']),
    r(5, 4, ['崁頂鄉', '林邊鄉', '南州鄉', '佳冬鄉']),
    r(6, 3, ['恆春鎮', '車城鄉', '滿州鄉', '枋山鄉', '獅子鄉', '牡丹鄉']),
    r(7, 1, ['琉球鄉']),
    i(8, 1, 'PLAINS_INDIGENOUS', '屏東縣之平地原住民'),
    i(9, 1, 'MOUNTAIN_INDIGENOUS', '三地門鄉及九如鄉、里港鄉、鹽埔鄉、高樹鄉之山地原住民'),
    i(10, 1, 'MOUNTAIN_INDIGENOUS', '瑪家鄉及屏東市、長治鄉、麟洛鄉、內埔鄉之山地原住民'),
    i(11, 1, 'MOUNTAIN_INDIGENOUS', '泰武鄉及萬丹鄉、萬巒鄉、竹田鄉之山地原住民'),
    i(12, 1, 'MOUNTAIN_INDIGENOUS', '來義鄉及潮州鎮、新埤鄉、新園鄉、崁頂鄉、南州鄉之山地原住民'),
    i(13, 1, 'MOUNTAIN_INDIGENOUS', '春日鄉及東港鎮、枋寮鄉、林邊鄉、佳冬鄉、琉球鄉之山地原住民'),
    i(14, 1, 'MOUNTAIN_INDIGENOUS', '獅子鄉及枋山鄉之山地原住民'),
    i(15, 1, 'MOUNTAIN_INDIGENOUS', '牡丹鄉及恆春鎮、車城鄉、滿州鄉之山地原住民'),
    i(16, 1, 'MOUNTAIN_INDIGENOUS', '霧臺鄉之山地原住民'),
  ],
  ILA: [
    r(1, 7, ['宜蘭市']),
    r(2, 2, ['頭城鎮']),
    r(3, 3, ['礁溪鄉']),
    r(4, 2, ['員山鄉']),
    r(5, 2, ['壯圍鄉']),
    r(6, 5, ['羅東鎮']),
    r(7, 3, ['五結鄉']),
    r(8, 4, ['冬山鄉']),
    r(9, 1, ['三星鄉', '大同鄉']),
    r(10, 2, ['蘇澳鎮', '南澳鄉']),
    i(11, 1, 'PLAINS_INDIGENOUS', '宜蘭縣之平地原住民'),
    i(
      12,
      1,
      'MOUNTAIN_INDIGENOUS',
      '大同鄉及宜蘭市、頭城鎮、礁溪鄉、員山鄉、壯圍鄉、三星鄉之山地原住民',
    ),
    i(13, 1, 'MOUNTAIN_INDIGENOUS', '南澳鄉及羅東鎮、五結鄉、冬山鄉、蘇澳鎮之山地原住民'),
  ],
  HUA: [
    r(1, 9, ['花蓮市']),
    r(2, 1, ['新城鄉', '秀林鄉']),
    r(3, 10, ['吉安鄉', '壽豐鄉', '鳳林鎮', '光復鄉', '豐濱鄉', '萬榮鄉']),
    r(4, 3, ['瑞穗鄉', '玉里鎮', '富里鄉', '卓溪鄉']),
    i(5, 4, 'PLAINS_INDIGENOUS', '花蓮市、新城鄉、秀林鄉、吉安鄉之平地原住民'),
    i(6, 2, 'PLAINS_INDIGENOUS', '壽豐鄉、鳳林鎮、萬榮鄉、光復鄉、豐濱鄉之平地原住民'),
    i(7, 1, 'PLAINS_INDIGENOUS', '瑞穗鄉、玉里鎮、富里鄉、卓溪鄉之平地原住民'),
    i(8, 1, 'MOUNTAIN_INDIGENOUS', '秀林鄉及花蓮市、新城鄉、吉安鄉、壽豐鄉之山地原住民'),
    i(9, 1, 'MOUNTAIN_INDIGENOUS', '萬榮鄉及鳳林鎮、光復鄉、豐濱鄉、瑞穗鄉之山地原住民'),
    i(10, 1, 'MOUNTAIN_INDIGENOUS', '卓溪鄉及玉里鎮、富里鄉之山地原住民'),
  ],
  TTT: [
    r(1, 10, ['臺東市', '蘭嶼鄉']),
    r(2, 1, ['卑南鄉', '延平鄉']),
    r(3, 2, ['東河鄉', '成功鎮', '長濱鄉']),
    r(4, 2, ['鹿野鄉', '關山鎮', '海端鄉', '池上鄉']),
    r(5, 1, ['太麻里鄉', '金峰鄉', '達仁鄉', '大武鄉']),
    r(6, 1, ['綠島鄉']),
    i(7, 3, 'PLAINS_INDIGENOUS', '臺東市之平地原住民'),
    i(8, 1, 'PLAINS_INDIGENOUS', '卑南鄉、蘭嶼鄉之平地原住民'),
    i(9, 1, 'PLAINS_INDIGENOUS', '太麻里鄉、金峰鄉、達仁鄉、大武鄉之平地原住民'),
    i(10, 1, 'PLAINS_INDIGENOUS', '鹿野鄉、延平鄉、關山鎮、海端鄉、池上鄉之平地原住民'),
    i(11, 2, 'PLAINS_INDIGENOUS', '東河鄉、綠島鄉、成功鎮、長濱鄉之平地原住民'),
    i(12, 1, 'MOUNTAIN_INDIGENOUS', '延平鄉及卑南鄉、東河鄉、成功鎮、長濱鄉之山地原住民'),
    i(13, 1, 'MOUNTAIN_INDIGENOUS', '海端鄉及鹿野鄉、關山鎮、池上鄉之山地原住民'),
    i(14, 1, 'MOUNTAIN_INDIGENOUS', '金峰鄉及太麻里鄉、臺東市、綠島鄉之山地原住民'),
    i(15, 1, 'MOUNTAIN_INDIGENOUS', '達仁鄉及大武鄉之山地原住民'),
    i(16, 1, 'MOUNTAIN_INDIGENOUS', '蘭嶼鄉之山地原住民'),
  ],
  PEN: [
    r(1, 11, ['馬公市']),
    r(2, 3, ['湖西鄉']),
    r(3, 2, ['白沙鄉']),
    r(4, 1, ['西嶼鄉']),
    r(5, 1, ['望安鄉']),
    r(6, 1, ['七美鄉']),
  ],
  KIN: [
    r(1, 10, ['金城鎮', '金寧鄉', '烏坵鄉']),
    r(2, 7, ['金湖鎮', '金沙鎮']),
    r(3, 2, ['烈嶼鄉']),
  ],
  LIE: [r(1, 5, ['南竿鄉']), r(2, 2, ['北竿鄉']), r(3, 1, ['莒光鄉']), r(4, 1, ['東引鄉'])],
  KEE: [
    r(1, 4, ['中正區']),
    r(2, 5, ['信義區']),
    r(3, 3, ['仁愛區']),
    r(4, 4, ['中山區']),
    r(5, 7, ['安樂區']),
    r(6, 3, ['暖暖區']),
    r(7, 4, ['七堵區']),
    i(8, 1, 'PLAINS_INDIGENOUS', '基隆市之平地原住民'),
    i(9, 1, 'MOUNTAIN_INDIGENOUS', '基隆市之山地原住民'),
  ],
  HSZ: [
    rv(1, 12, '東區', [
      '東門里',
      '榮光里',
      '成功里',
      '育賢里',
      '中正里',
      '親仁里',
      '文華里',
      '復中里',
      '三民里',
      '公園里',
      '東園里',
      '東山里',
      '東勢里',
      '光復里',
      '前溪里',
      '水源里',
      '千甲里',
      '綠水里',
      '埔頂里',
      '仙宮里',
      '龍山里',
      '新莊里',
      '關新里',
      '仙水里',
      '金山里',
      '建功里',
      '光明里',
      '立功里',
      '軍功里',
      '武功里',
      '豐功里',
      '科園里',
      '關東里',
      '建華里',
      '錦華里',
      '復興里',
    ]),
    rv(2, 4, '東區', [
      '南門里',
      '關帝里',
      '南市里',
      '福德里',
      '振興里',
      '新興里',
      '竹蓮里',
      '南大里',
      '寺前里',
      '下竹里',
      '頂竹里',
      '光鎮里',
      '高峰里',
      '柴橋里',
      '新光里',
      '湖濱里',
      '明湖里',
    ]),
    rv(3, 2, '北區', [
      '客雅里',
      '中雅里',
      '育英里',
      '曲溪里',
      '西雅里',
      '南勢里',
      '大鵬里',
      '西門里',
      '仁德里',
      '潛園里',
      '中央里',
      '崇禮里',
      '石坊里',
      '興南里',
      '台溪里',
    ]),
    rv(4, 9, '北區', [
      '北門里',
      '中興里',
      '大同里',
      '中山里',
      '長和里',
      '新民里',
      '民富里',
      '水田里',
      '文雅里',
      '光田里',
      '士林里',
      '福林里',
      '古賢里',
      '湳雅里',
      '舊社里',
      '武陵里',
      '南寮里',
      '舊港里',
      '康樂里',
      '港北里',
      '中寮里',
      '海濱里',
      '磐石里',
      '新雅里',
      '光華里',
      '金華里',
      '境福里',
      '金竹里',
      '湳中里',
      '金雅里',
    ]),
    rv(5, 6, '香山區', [
      '頂埔里',
      '中埔里',
      '埔前里',
      '牛埔里',
      '樹下里',
      '浸水里',
      '虎林里',
      '虎山里',
      '港南里',
      '大庄里',
      '美山里',
      '朝山里',
      '東香里',
      '香山里',
      '香村里',
      '海山里',
      '鹽水里',
      '內湖里',
      '南港里',
      '中隘里',
      '南隘里',
      '大湖里',
      '茄苳里',
      '頂福里',
    ]),
    i(6, 1, 'PLAINS_INDIGENOUS', '新竹市之平地原住民'),
    i(7, 1, 'MOUNTAIN_INDIGENOUS', '新竹市之山地原住民'),
  ],
  CYI: [r(1, 10, ['東區']), r(2, 13, ['西區'])],
};

export const councilDistricts: readonly CouncilDistrict[] = Object.entries(districtInputs).flatMap(
  ([jurisdictionId, districts]) =>
    districts.map((district) => ({
      ...district,
      id: `${jurisdictionId}-COUNCIL-${district.number}`,
      jurisdictionId,
    })),
);

export function getCouncilDistricts(jurisdictionId: string) {
  return councilDistricts.filter((district) => district.jurisdictionId === jurisdictionId);
}

export function getRegionalCouncilDistricts(jurisdictionId: string) {
  return getCouncilDistricts(jurisdictionId).filter((district) => district.kind === 'REGIONAL');
}

export function findRegionalCouncilDistricts(
  jurisdictionId: string,
  township: string,
  village?: string,
) {
  return getRegionalCouncilDistricts(jurisdictionId).filter(
    (district) =>
      district.townships.includes(township) ||
      district.villageGroups.some(
        (group) =>
          group.township === township &&
          (village === undefined || group.villages.includes(village)),
      ),
  );
}

export function needsVillageCouncilGeometry(jurisdictionId: string) {
  return getRegionalCouncilDistricts(jurisdictionId).some(
    (district) => district.villageGroups.length > 0,
  );
}
